INSERT INTO loaikhach VALUES (1, 'Diamond');
INSERT INTO loaikhach VALUES (2, 'Platinium');
INSERT INTO loaikhach VALUES (3, 'Gold');
INSERT INTO loaikhach VALUES (4, 'Silver');
INSERT INTO loaikhach VALUES (5, 'Member');
INSERT INTO vitri VALUES (1, 'LeTan');
INSERT INTO vitri VALUES (2, 'PhucVu');
INSERT INTO vitri VALUES (3, 'ChuyenVien');
INSERT INTO vitri VALUES (4, 'GiamSat');
INSERT INTO vitri VALUES (5, 'QuanLy');
INSERT INTO vitri VALUES (6, 'GiamDoc');
INSERT INTO trinhdo VALUES (1, 'TrungCap');
INSERT INTO trinhdo VALUES (2, 'CaoDang');
INSERT INTO trinhdo VALUES (3, 'DaiHoc');
INSERT INTO trinhdo VALUES (4, 'SauDaiHoc');
INSERT INTO bophan VALUES (1, 'Sale–Marketing');
INSERT INTO bophan VALUES (2, 'HanhChinh');
INSERT INTO bophan VALUES (3, 'PhucVu');
INSERT INTO bophan VALUES (4, 'QuanLy');
INSERT INTO kieuthue VALUES (1, 'Year', 3000);
INSERT INTO kieuthue VALUES (2, 'Month', 300);
INSERT INTO kieuthue VALUES (3, 'Day', 10);
INSERT INTO kieuthue VALUES (4, 'Hour', 1);
INSERT INTO loaidichvu VALUES (1, 'Villa,FreePickUp2Way,PoolArea:30,Floors:2');
INSERT INTO loaidichvu VALUES (2, 'House,FreePickUp,Floors:2'); 
INSERT INTO loaidichvu VALUES (3, 'Room,Wifi,2WaterBottles');
INSERT INTO dichvu VALUES (1, 'Villa', 150, 2, '5', '1000000', 1, 1, '');
INSERT INTO dichvu VALUES (2, 'Villa', 150, 2, '5', '1200000', 2, 1, '');
INSERT INTO dichvu VALUES (3, 'Villa', 150, 2, '5', '1400000', 3, 1, '');
INSERT INTO dichvu VALUES (4, 'House', 100, 2, '4', '500000', 1, 2, '');
INSERT INTO dichvu VALUES (5, 'House', 100, 2, '4', '600000', 2, 2, '');
INSERT INTO dichvu VALUES (6, 'House', 100, 2, '4', '700000', 3, 2, '');
INSERT INTO dichvu VALUES (7, 'Room', 50, 1, '2', '200000', 3, 3, '');
INSERT INTO dichvu VALUES (8, 'Room', 50, 1, '2', '300000', 4, 3, '');
INSERT INTO dichvudikem VALUES (1, 'massage', 300000, 10, '');
INSERT INTO dichvudikem VALUES (2, 'karaoke', 500000, 10, '');
INSERT INTO dichvudikem VALUES (3, 'food', 50000, 100, '');
INSERT INTO dichvudikem VALUES (4, 'drink', 20000, 100, '');
INSERT INTO dichvudikem VALUES (5, 'CarRent', 300000, 5, '');


